development:
  password: a1e2771931b077f218dc21ae50d5867c
  theme_id: "73253748847"
  store: blomsterbutikken.myshopify.com
  ignore_files:
    - config/settings_data.json
    - assets/*.jpg
    - locales/*.json
com:
  password: a1e2771931b077f218dc21ae50d5867c
  theme_id: "73253748847"
  store: blomsterbutikken.myshopify.com
  ignore_files:
    - config/settings_data.json
    - assets/*.jpg
    - locales/*.json
